# Generated by Django 2.0.6 on 2018-07-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tagline',
            field=models.TextField(default='DEFAULT'),
        ),
    ]
