# Generated by Django 2.0.6 on 2018-07-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_photo_tagline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='tagline',
        ),
        migrations.AddField(
            model_name='photo',
            name='color_tag',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
