# Generated by Django 2.0.6 on 2018-07-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180707_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='created_date',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
