# Generated by Django 2.0.6 on 2018-07-09 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_photo_created_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
