# Generated by Django 2.0.6 on 2018-07-09 14:21

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='images')),
                ('color_tag', models.CharField(default='NULL', max_length=100)),
                ('created_date', models.CharField(default='NULL', max_length=100)),
            ],
        ),
    ]
